PROGRAM_NAME='AdvancedEvents'


DEFINE_CONSTANT

INTEGER PAGE_VOLUME_LVL= 8      // page volume level 

INTEGER TUNE_MODE_CH   = 301    // On=Seek Off=Tune
INTEGER KEYPAD_LOCK_CH = 302    // keypad lock channel 
INTEGER PAGE_ENABLE_CH = 305

INTEGER SIRIUS_CATEGORY_UP_CH = 308
INTEGER SIRIUS_CATEGORY_DN_CH = 307
